// The hook events each agent's managed installer subscribes to — ONE list per agent, shared by
// every installer (local desktop, Server Edition, and the SSH remote installer).
//
// They used to be declared twice, and the copies had drifted: the remote installer subscribed
// claude to `SessionStart`/`SubagentStop` but NOT to `StopFailure`/`PermissionRequest` (so a
// remote agent's errored turn stuck on "working" and its permission prompts arrived late), and it
// subscribed gemini to CLAUDE's event names, which gemini never fires — remote gemini nodes
// reported no status at all.
//
// The drift also produced a broken settings.json on any machine where two installers ran: each
// rewrites only the events IT knows, so a stale instance's command survived on every event the
// other list lacked. Keeping the lists here is what makes an install a complete rewrite.

/**
 * One managed hook subscription: an event name, or an event name PLUS the matcher to write for it.
 * Only grok needs the second form — its tool-event `matcher` is a real REGEX
 * (`~/.grok/docs/user-guide/10-hooks.md:153`), so a bare `*` is not a valid match-all but an invalid
 * pattern, and the expected failure is silence: the tool events simply never fire. We write `.*`.
 * That is read off the docs, not observed — no hook was ever seen firing here (see GROK_HOOK_EVENTS).
 * claude/codex/gemini stay plain strings, so their emitted config is byte-identical to what it has
 * always been.
 */
export type ManagedHookEvent = string | { event: string; matcher: string }

/** Claude Code hook events. Each maps to a `NormalizedAgentEvent` in shared/agents/normalize.ts. */
export const CLAUDE_HOOK_EVENTS = [
  'SessionStart',
  'UserPromptSubmit',
  'Stop',
  // Fires INSTEAD of Stop when the turn ends on an API/model error — without it the
  // status badge sticks on "working" after any errored turn.
  'StopFailure',
  'Notification',
  // Dedicated permission-prompt signal (→ blocked), more direct than Notification.
  'PermissionRequest',
  'SessionEnd',
  'PreToolUse',
  'PostToolUse'
] as const

/**
 * Gemini CLI hook events (→ normalizeGemini) — its own names, NOT Claude's.
 *
 * Gemini publishes ELEVEN events; these are the seven we can act on. The four left out are
 * deliberate, all per gemini 0.54.4's bundled `docs/hooks/reference.md`:
 *   - `AfterModel` fires for EVERY streamed chunk (reference.md:236-237, "Fired for every chunk
 *     generated by the model"; its `fireAfterModelEvent(request, chunk)` runs inside the chunk
 *     loop), so subscribing would spawn a hook process per chunk. It is also the one that carries
 *     `llm_response.usageMetadata.totalTokenCount` — the one number worth having — which is why the
 *     gemini context meter reads the TRANSCRIPT instead of subscribing here (`core/gemini-session.ts`
 *     `geminiContextParse`, fed by the same tail claude's meter uses). Do not "just add AfterModel"
 *     to get the tokens: the meter already has them, and this event would cost a process per chunk.
 *   - `BeforeModel` is NOT per-chunk — it fires once per model request (reference.md:187-190,
 *     "Fires before sending a request to the LLM"). It is left out for the plain reason the two
 *     below are: it reports nothing we render. A turn's start is already `BeforeAgent`, and a
 *     second working→working event per request would only add hook processes.
 *   - `BeforeToolSelection` (reference.md:204-219) and `PreCompress` (reference.md:287-297) have
 *     no state we render today.
 *
 * `Notification` is the important addition: it is gemini's ONLY signal that the user is being
 * asked something (`notification_type: "ToolPermission"`, reference.md:272-285). Without it a
 * gemini node sat on RUNNING while it waited for a permission answer, because the last event we
 * heard was `BeforeTool`.
 */
export const GEMINI_HOOK_EVENTS = [
  'BeforeAgent',
  'AfterAgent',
  'AfterTool',
  'BeforeTool',
  'Notification',
  'SessionStart',
  'SessionEnd'
] as const

/**
 * GitHub Copilot CLI hook events (→ normalizeCopilot). Copilot uses the same PascalCase event
 * names as Claude but a different config-file shape, so the subscription list stays shared while
 * its installer lives in core/agents/hooks/copilot.ts.
 *
 * `PermissionRequest` is deliberately absent. Copilot documents that hook as a decision hook that
 * can alter the permission result, whereas nodeterm only observes status. Its `Notification`
 * event carries the closed `permission_prompt` / `elicitation_dialog` signals we need without
 * participating in authorization. `ErrorOccurred` is also omitted: recoverable API/tool errors
 * can occur before a turn continues, so treating one as a terminal state would clear RUNNING early.
 */
export const COPILOT_HOOK_EVENTS = [
  'SessionStart',
  'UserPromptSubmit',
  'PreToolUse',
  'PostToolUse',
  'PostToolUseFailure',
  'Stop',
  'Notification',
  'SessionEnd'
] as const

/**
 * Grok hook events (→ normalizeGrok). Grok's shipped 1.0.0 docs list fourteen
 * (`~/.grok/docs/user-guide/10-hooks.md:84-101`); nine are subscribed — the ones `normalizeGrok` has
 * a mapping for. The other five are left off deliberately: PermissionDenied is a post-decision event
 * we would have nothing to do with, SubagentStart/SubagentStop drive subagent cards that are not
 * built for grok, and PreCompact/PostCompact have no consumer. No event here was ever seen FIRING —
 * that needs a logged-in session, which the branch never had — so subscribing one is a claim about
 * the docs, not a measurement. Grok skips hook event names it does not recognize (that is how a shared Claude
 * settings file loads at all), so adding one later is safe.
 */
export const GROK_HOOK_EVENTS: readonly ManagedHookEvent[] = [
  'SessionStart',
  'UserPromptSubmit',
  'Stop',
  // Fires INSTEAD of Stop when the turn dies on an API error — without it the badge sticks.
  'StopFailure',
  'Notification',
  'SessionEnd',
  // The matcher is a REGEX, and an omitted one already matches everything
  // (~/.grok/docs/user-guide/10-hooks.md:153) — so this is not a requirement, it is an explicit
  // statement of "every tool". It is spelled `.*` and never `*`, because a bare `*` is not a
  // valid regex at all (nothing to repeat) and the failure mode is silence: the tool lifecycle
  // hooks simply never fire, so RUNNING clears mid-turn on a long tool call with nothing saying why.
  { event: 'PreToolUse', matcher: '.*' },
  { event: 'PostToolUse', matcher: '.*' },
  { event: 'PostToolUseFailure', matcher: '.*' }
]
